<?php

namespace ReclamationBundle\Repository;

/**
 * CatReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatReclamationRepository extends \Doctrine\ORM\EntityRepository
{
}
