<?php

namespace ReclamationBundle\Repository;

/**
 * ProduitRecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRecRepository extends \Doctrine\ORM\EntityRepository
{
}
