PubextBundle\Entity\Pubext:
    type: entity
    table: pubext
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nompubext:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        datedebutpubext:
            type: date
            nullable: false
        dateexppubext:
            type: date
            nullable: false
        photo:
            type: blob
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
