pubext:
    resource: "@PubextBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

favoris:
    resource: "@FavorisBundle/Resources/config/routing.yml"
    prefix:   /pidev

commande:
    resource: "@CommandeBundle/Resources/config/routing.yml"
    prefix:   /pidev

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /rec

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /pidev

annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"