<?php

namespace PubextBundle\Repository;

/**
 * PubextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubextRepository extends \Doctrine\ORM\EntityRepository
{
}
