cat_index:
    path:     /
    defaults: { _controller: "AnnoncesBundle:Categorieannonce:index" }
    methods:  GET

cat_show:
    path:     /{id}/show
    defaults: { _controller: "AnnoncesBundle:Categorieannonce:show" }
    methods:  GET

cat_new:
    path:     /new
    defaults: { _controller: "AnnoncesBundle:Categorieannonce:new" }
    methods:  [GET, POST]

cat_edit:
    path:     /{id}/edit
    defaults: { _controller: "AnnoncesBundle:Categorieannonce:edit" }
    methods:  [GET, POST]

cat_delete:
    path:     /{id}/delete
    defaults: { _controller: "AnnoncesBundle:Categorieannonce:delete" }
    methods:  DELETE
